### ISSUE TITLE
Bug in walk

### ISSUE THREAD

**Issue by eGavr** [andrewblond/bem-walk#8]
Пытаюсь обойти блоки волкером и получаю

```bash
/Users/gavryushin/job/bemhint/node_modules/bem-walk/lib/schemes/nested.js:53
pth === 3 && dirType === 'blockMod' && dirNotation.block === notation.block &&
                                                                     ^
TypeError: Cannot read property 'block' of undefined
    at /Users/gavryushin/job/bemhint/node_modules/bem-walk/lib/schemes/nested.js:53:93
    at /Users/gavryushin/job/bemhint/node_modules/bem-walk/lib/index.js:49:21
    at Object.oncomplete (fs.js:107:15)
```

**Comment by eGavr** [comment]
Суть в следующем:
`spin_theme_white_blah` - эта, после парсинга с помощью [bem-naming](https://github.com/bem/bem-naming) получается `undefined`.

**Comment by andrewblond** [comment]
Спасибо за отзыв! Кинешь PR?
